[tool.poetry]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
authors = ["Replit user"]

[tool.poetry.dependencies]
python = ">=3.10"
openai = "1.57.0"
pillow = ">=11.0.0"